*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZGCTS_POC_REGU01.
                    "TABLEFRAME_ZGCTS_POC_REG
INCLUDE LZGCTS_POC_REGU02.
                    "TABLEPROC_ZGCTS_POC_REG